just install it properly

diff --git a/.github/workflows/dockcross.yml b/.github/workflows/dockcross.yml
--- a/.github/workflows/dockcross.yml
+++ b/.github/workflows/dockcross.yml
@@ -53,18 +53,30 @@ jobs:
     #         ./dockcross bash -c "conan version || echo could not run conan version"
     #         ./dockcross conan profile new --detect default
 
-      - name: install libffi
-        run: |
-            ./dockcross bash -c "conan --version || conan version || echo could not run conan version"
-            ./dockcross bash -c "conan profile detect --force && conan install . --output-folder=build --build=missing || echo notv2"
-            # if conanv1 we don't really need to do a profile
-            ./dockcross bash -c "(mkdir -p /home/runner/.conan/; echo 'conan-center https://center.conan.io False' >> /home/runner/.conan/registry.txt && conan install . --build=missing) || echo notv1"
-            # do a v2 conan install
-            ./dockcross bash -c "conan install . --output-folder=build --build=missing --name libffi --version 3.4.4 || echo notv2"
-            # do a v1 conan install
-            ./dockcross bash -c "conan install . --build=missing libffi/3.4.4@conan/stable || echo notv1"
+    #   - name: install libffi
+    #     run: |
+    #         ./dockcross bash -c "conan --version || conan version || echo could not run conan version"
+    #         ./dockcross bash -c "conan profile detect --force && conan install . --output-folder=build --build=missing || echo notv2"
+    #         # if conanv1 we don't really need to do a profile
+    #         ./dockcross bash -c "(mkdir -p /home/runner/.conan/; echo 'conan-center https://center.conan.io False' >> /home/runner/.conan/registry.txt && conan install . --build=missing) || echo notv1"
+    #         # do a v2 conan install
+    #         ./dockcross bash -c "conan install . --output-folder=build --build=missing --name libffi --version 3.4.4 || echo notv2"
+    #         # do a v1 conan install
+    #         ./dockcross bash -c "conan install . --build=missing libffi/3.4.4@conan/stable || echo notv1"
             
 
+      - name: install libffi
+        run: |
+            ./dockcross bash -c "
+                wget https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz
+                  tar xzf libffi-3.4.6.tar.gz
+                    cd libffi-3.4.6
+                   ./configure --prefix=/usr
+                   make
+                   make install
+                   "
+
+          
 
         #     # Conan v1 commands
         #     ./dockcross bash -c "mkdir -p /home/runner/.conan/; echo 'conan-center https://center.conan.io False' >> /home/runner/.conan/registry.txt"
